GET http://localhost:55555/admin/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg3MDI3ODM1LCJleHAiOjE2ODcxMTQyMzV9.PHdR3q-xM0FZzw3mJjIGTR1AwksbGWxMh0QPhCpTGHk
